updated with most recent version (still in development)

diff --git a/inspiration/webserver_utils/bin/add_server b/inspiration/webserver_utils/bin/add_server
--- a/inspiration/webserver_utils/bin/add_server
+++ b/inspiration/webserver_utils/bin/add_server
@@ -8,13 +8,22 @@ WS_ETC_DIR="$WS_ROOT_DIR/etc/webserver_utils"
 . "$WS_ETC_DIR/include/functions.sh"
 . "$WS_ETC_DIR/webserver.conf"
 
+SKEL_DIR_DEFAULT='/var/www/skel_static'
+BASE_DIR_DEFAULT='/var/www'
+BLOCKS_DEFAULT='10485760'
+PHP_VERSION_DEFAULT='7.4'
+
+REDIRECT_MODE=false
+REDIRECT_TARGET=
+ALIAS_MODE=false
+
 DOMAIN=
 LOGIN=
 HOME_DIR=
-SKEL_DIR='/var/www/skel_static' # default
-BASE_DIR='/var/www' # default
-BLOCKS='10485760' # default: 10G quota
-PHP_VERSION='7.4' # default: php7.4 unit
+SKEL_DIR=$SKEL_DIR_DEFAULT
+BASE_DIR=$BASE_DIR_DEFAULT
+BLOCKS=$BLOCKS_DEFAULT
+PHP_VERSION=$PHP_VERSION_DEFAULT
 PHP_POOL_CONF=
 PHP_POOL_SOCK=
 NGINX_CONF=
@@ -23,30 +32,47 @@ RELOAD_NGINX= # default: don't reload nginx on success
 
 usage() {
 	cat <<USAGE
-Usage: add_server [options] DOMAIN LOGIN
+Usage: add_server [options...] DOMAIN LOGIN
+   or: add_server [-y] [--reload_nginx] --alias DOMAIN LOGIN
+   or: add_server [--reload_nginx] --redirect[=TARGET] DOMAIN LOGIN
+   or: add_server -y [--reload_nginx] --redirect=TARGET DOMAIN LOGIN
 
+Behavior:
+  -r, --redirect[=TARGET]   create a new redirect to TARGET in the existing
+                            NGINX configuration for LOGIN. TARGET must be given
+                            when using the 'y' option. if another redirect with
+                            the same TARGET already exists, DOMAIN will be
+                            added as an alias for that redirect instead.
+
+  -a, --alias               don't create a new user, home directory, or new
+                            configurations for LOGIN, instead append DOMAIN to
+                            the existing configuration for LOGIN - useful for
+                            multisite installations.
 Options:
   -h, --help                show this help
   -k, --skel=SKEL_DIR       use this alternative skeleton directory
-  -b, --base-dir BASE_DIR   base directory for the home directory of the
-                            new account
+  -b, --base-dir BASE_DIR   base directory for the home directory of the new
+                            account
   -q, --quota=BLOCKS        specify the quota in 1K blocks for the virtual
-			    server user. defaults to '10485760' (10GB)
+                            server user. defaults to '10485760' (10GB)
   -p, --php=PHP_VERSION     specify a php version to use for the virtual
-			    server. defaults to '7.4'
-  -y, --yes, --assume-yes   assume "yes" or "y" at all prompts
+                            server. defaults to '7.4'
+  -y, --yes, --assume-yes   assume "yes" or "y" at all prompts, sets non-
+                            interactive operation
   --no_create_database      don't create a database for the virtual server
   --reload_nginx            reload the NGINX webserver on successful virtual
-			    server creation
+                            server creation
 USAGE
 }
 
 parse_args() {
 	argc=$1
 	argv=$2
-	SHORTOPTS=":hk:b:q:y"
+	SHORTOPTS=":hr::ak:b:q:y"
 	LONGOPTS=(
 		"help:$no_argument::h"
+		"redirect:$optional_argument::r"
+		"alias:$no_argument::a"
 		"skel:$required_argument::k"
 		"base-dir:$required_argument::b"
 		"quota:$required_argument::q"
@@ -56,11 +82,39 @@ parse_args() {
 		"no-create-database:$no_argument:NO_CREATE_DATABASE:true"
 		"reload-nginx:$no_argument:RELOAD_NGINX:true"
 	)
+	incompat=false
 
 	while [ $optind -lt $argc ]; do
 		while true; do
 			getopt_long $argc $argv $SHORTOPTS $LONGOPTS
-			case $optret in
+			if [[ " k b q p no-create-database " =~ " $optopt " ]]; then
+				if $REDIRECT_MODE; then
+					>&2 echo "$EXECNAME: option '$optopt' is not compatiable with redirect mode"
+					usage
+					return 1
+				elif $ALIAS_MODE; then
+					>&2 echo "$EXECNAME: option '$optopt' is not compatiable with alias mode"
+					usage
+					return 1
+				else
+					incompat=true
+				fi
+			elif [ "$optopt" = "r" ]; then
+				if  $incompat || $ALIAS_MODE; then
+					>&2 echo "$EXECNAME: redirect mode is incompatible with the selected options"
+					usage
+					return 1
+				fi
+			elif [ "$optopt" = "a" ]; then
+				if $incompat || $REDIRECT_MODE; then
+					>&2 echo "$EXECNAME: alias mode is incompatible with the selected options"
+					usage
+					return 1
+				fi
+			fi
+			case "$optret" in
+				r)  REDIRECT_MODE=true;REDIRECT_TARGET=$optarg;;
+				a)  ALIAS_MODE=true;;
 				k)  SKEL_DIR=$optarg;;
 				b)  BASE_DIR=$optarg;;
 				q)  BLOCKS=$optarg;;
@@ -99,6 +153,41 @@ parse_args() {
 	[ -z "$RELOAD_NGINX" ] && RELOAD_NGINX=false || RELOAD_NGINX=true
 	[ -z "$yesno_yes" ] && yesno_yes=false || yesno_yes=true
 
+	$REDIRECT_MODE && $yesno_yes && [ -z "$REDIRECT_TARGET" ] && >&2 echo "$EXECNAME: a redirect target must be explicitly given when non-interactive" && usage && return 1
+
+	return 0
+}
+
+get_server_names() {
+	filename=$1
+        local -n server_names_out=$2
+	block_index=$3
+
+	matches="$(grep -ne '^[^#]*server_name' $filename)"
+	[ $? -ne 0 ] && return 1
+        blocks=( $(echo "$matches" | awk -F':' '{print $1}') )
+	[ $3 -gt ${#blocks} ] && return 1
+	
+	server_names_out=( $(sed -e $(echo "${blocks[$block_index]},/;/\!d" | sed 's/\\!/!/g') -e 's/\s\+/\n/g' $filename | sed 's/server_name//;s/;//;/^$/d') )
+	return 0
+}
+
+set_server_names() {
+	filename=$1
+	local -n server_names_in=$2
+	block_index=$3
+
+	matches="$(grep -ne '^[^#]*server_name' $filename)"
+	[ $? -ne 0 ] && return 1
+        blocks=( $(echo "$matches" | awk -F':' '{print $1}') )
+	[ $3 -gt ${#blocks} ] && return 1
+
+	#cp $filename $filename.orig
+
+	server_names="${server_names_in[@]}"
+	#sed -e "${blocks[$block_index]},/;/{/;/{s/^.*\$/\tserver_name $server_names ;/;:a;n;ba;};d}" $filename.orig > $filename
+	sed -e "${blocks[$block_index]},/;/{/;/{s/^.*\$/\tserver_name $server_names ;/;:a;n;ba;};d}" $filename
+
 	return 0
 }
 
@@ -108,12 +197,29 @@ validate() {
 		>&2 echo "$EXECNAME: '$DOMAIN' is not a valid domain"
 		return 1
 	fi
+
+	NGINX_CONF=$WS_NGINX_CONF_DIR/$LOGIN.conf
 	
 	# LOGIN
 	if ! [[ $LOGIN =~ ^[a-z][a-z0-9-]{0,30}$ ]]; then
 		>&2 echo "$EXECNAME: '$LOGIN' is not a valid username"
 		return 1
 	fi
+
+	if $ALIAS_MODE || $REDIRECT_MODE; then
+		if ! grep -qe "^$LOGIN:" "$WS_PASSWD_FILE"; then
+			>&2 echo "$EXECNAME: user '$LOGIN' must exist"
+			return 1
+		fi
+		if ! checkfile $NGINX_CONF f w ; then
+			>&2 echo "$EXECNAME: user '$LOGIN' must have an NGINX configuration at '$NGINX_CONF'"
+			return 1
+		fi
+		# make sure DOMAIN isn't already being used in a server_name statement
+
+		return 0
+	fi
+	
 	if grep -qe "^$LOGIN:" "$WS_PASSWD_FILE"; then
 		>&2 echo "$EXECNAME: user '$LOGIN' already exists"
 		return 1
@@ -121,12 +227,12 @@ validate() {
 
 	# USERADD STUFF
 	SKEL_DIR=$(echo "$SKEL_DIR"|sed 's/\/\+/\//g;s/\/$//')
-	if ! checkfile $SKEL_DIR d a w ; then
+	if ! checkfile $SKEL_DIR a d w ; then
 		usage
 		return 1
 	fi
 	BASE_DIR=$(echo "$BASE_DIR"|sed 's/\/\+/\//g;s/\/$//')
-	if ! checkfile $BASE_DIR d a w ; then
+	if ! checkfile $BASE_DIR a d w ; then
 		usage
 		return 1
 	fi
@@ -153,7 +259,7 @@ validate() {
 		usage
 		return 1
 	fi
-	PHP_POOL_CONF=$PHP_POOL_DIR/$DOMAIN.conf
+	PHP_POOL_CONF=$PHP_POOL_DIR/$LOGIN.conf
 	PHP_POOL_SOCK=$WS_PHP_SOCK_DIR/php$PHP_VERSION-fpm-$LOGIN.sock
 	# TODO: add php version validation ( check for unit file templates )
 
@@ -163,10 +269,26 @@ validate() {
 		usage
 		return 1
 	fi
-	NGINX_CONF=$WS_NGINX_CONF_DIR/$DOMAIN.conf
 }
 
-main() {
+main_redirect() {
+	# find redirect block in nginx config
+	# add alias if redirect block found
+	# otherwise, add new redirect block to end of config
+	return 0
+}
+
+main_alias() {
+	# find first block in nginx config
+	names=
+	get_server_names $NGINX_CONF names 0 || return 1
+	names=( ${names[@]} "$DOMAIN" )
+	# add alias to that
+	set_server_names $NGINX_CONF names 0 || return 1
+	return 0
+}
+
+main_default() {
 	# TODO: all this other stuff
 
 	echo "$EXECNAME: setting up user..."
@@ -233,12 +355,6 @@ MYSQLDOC
 
 	# startup php unit
 	# link nginx config
-	if [ ! -z $RELOAD_NGINX ]; then
-		echo "$EXECNAME: reloading NGINX..."
-		# test & reload nginx
-		# if there's a problem, fail without reload, leave everything the way it is.
-	fi
-
 	return 0
 }
 
@@ -309,30 +425,75 @@ WS_NGINX_ETC_DIR = $WS_NGINX_ETC_DIR
 WS_NGINX_CONF_DIR = $WS_NGINX_CONF_DIR
 WS_TEMPLATE_DIR = $WS_TEMPLATE_DIR
 
-EOF
+yesno_yes = $yesno_yes
 
-cat <<EOF
-DOMAIN = $DOMAIN
-LOGIN = $LOGIN
-HOME_DIR = $HOME_DIR
-SKEL_DIR = $SKEL_DIR (default is '/var/www/skel_static')
-BASE_DIR = $BASE_DIR (default is '/var/www')
-BLOCKS = $BLOCKS (default is '10485760')
-PHP_VERSION = $PHP_VERSION (default is '7.4')
 PHP_POOL_CONF = $PHP_POOL_CONF
 PHP_POOL_SOCK = $PHP_POOL_SOCK
 NGINX_CONF = $NGINX_CONF
-NO_CREATE_DATABASE = $NO_CREATE_DATABASE
-RELOAD_NGINX = $RELOAD_NGINX
-yesno_yes = $yesno_yes
+
 PHP_CONF_TEMPLATE = $PHP_CONF_TEMPLATE
 NGINX_CONF_TEMPLATE = $NGINX_CONF_TEMPLATE
+
+EOF
+
+if $REDIRECT_MODE; then
+	if [ -z $REDIRECT_TARGET]; then
+		# TODO: have user interactively chose new or existing target
+		echo "choose a redirect target"
+	fi
+
+	cat <<EOF
+REDIRECT OPTIONS
+
+DOMAIN = $DOMAIN
+LOGIN = $LOGIN
+REDIRECT_TARGET = $REDIRECT_TARGET
+RELOAD_NGINX = $RELOAD_NGINX
 
 Please review the options above.
 EOF
 
-yesno "Do you wish to continue?" "N" "" || exit 0
+	yesno "Do you wish to continue?" "N" "" || exit 0
 
-main || exit 1
+	main_redirect || exit 1
+elif $ALIAS_MODE; then
+	cat <<EOF
+ALIAS OPTIONS
+
+DOMAIN = $DOMAIN
+LOGIN = $LOGIN
+RELOAD_NGINX = $RELOAD_NGINX
+
+Please review the options above.
+EOF
+
+	yesno "Do you wish to continue?" "N" "" || exit 0
+
+	main_alias || exit 1
+else
+	cat <<EOF
+DOMAIN = $DOMAIN
+LOGIN = $LOGIN
+HOME_DIR = $HOME_DIR
+SKEL_DIR = $SKEL_DIR (default is '$SKEL_DIR_DEFAULT')
+BASE_DIR = $BASE_DIR (default is '$BASE_DIR_DEFAULT')
+BLOCKS = $BLOCKS (default is '$BLOCKS_DEFAULT')
+PHP_VERSION = $PHP_VERSION (default is '$PHP_VERSION_DEFAULT')
+NO_CREATE_DATABASE = $NO_CREATE_DATABASE
+RELOAD_NGINX = $RELOAD_NGINX
+
+Please review the options above.
+EOF
+
+	yesno "Do you wish to continue?" "N" "" || exit 0
+
+	main_default || exit 1
+fi
+
+if $RELOAD_NGINX; then
+	echo "$EXECNAME: reloading NGINX..."
+	# test & reload nginx
+	# if there's a problem, fail without reload, leave everything the way it is.
+fi
 
 exit 0
